// ==========================================
// ZOLOFRESH - Generated Catalog Data (Excel Source)
// Generated: 2026-08-27 14:30:49
// ==========================================

const DEFAULT_CATEGORIES = [
  {
    "id": 1,
    "category_name": "Fruits & Fresh Produce",
    "slug": "fruits-fresh-produce",
    "parent_id": null,
    "status": true
  },
  {
    "id": 2,
    "category_name": "Staples & Grains",
    "slug": "staples-grains",
    "parent_id": null,
    "status": true
  },
  {
    "id": 3,
    "category_name": "Superfoods & Snacks",
    "slug": "superfoods-snacks",
    "parent_id": null,
    "status": true
  },
  {
    "id": 4,
    "category_name": "Handlooms & Handicrafts",
    "slug": "handlooms-handicrafts",
    "parent_id": null,
    "status": true
  },
  {
    "id": 5,
    "category_name": "Puja Essentials & Kits",
    "slug": "puja-essentials-kits",
    "parent_id": null,
    "status": true
  },
  {
    "id": 6,
    "category_name": "Shahi Litchi",
    "slug": "shahi-litchi",
    "parent_id": 1,
    "status": true
  },
  {
    "id": 7,
    "category_name": "Jardalu Mango",
    "slug": "jardalu-mango",
    "parent_id": 1,
    "status": true
  },
  {
    "id": 8,
    "category_name": "Katarni Rice",
    "slug": "katarni-rice",
    "parent_id": 2,
    "status": true
  },
  {
    "id": 9,
    "category_name": "Bhagalpuri Rice",
    "slug": "bhagalpuri-rice",
    "parent_id": 2,
    "status": true
  },
  {
    "id": 10,
    "category_name": "Chana Ka Sattu",
    "slug": "chana-ka-sattu",
    "parent_id": 2,
    "status": true
  },
  {
    "id": 11,
    "category_name": "Chura / Poha",
    "slug": "chura-poha",
    "parent_id": 2,
    "status": true
  },
  {
    "id": 12,
    "category_name": "Mithila Makhana",
    "slug": "mithila-makhana",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 13,
    "category_name": "Bhuna Makhana",
    "slug": "bhuna-makhana",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 14,
    "category_name": "Silao Khaja",
    "slug": "silao-khaja",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 15,
    "category_name": "Tilkut",
    "slug": "tilkut",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 16,
    "category_name": "Thekua",
    "slug": "thekua",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 17,
    "category_name": "Jaggery",
    "slug": "jaggery",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 18,
    "category_name": "Traditional Sweets",
    "slug": "traditional-sweets",
    "parent_id": 3,
    "status": true
  },
  {
    "id": 19,
    "category_name": "Madhubani Paintings",
    "slug": "madhubani-paintings",
    "parent_id": 4,
    "status": true
  },
  {
    "id": 20,
    "category_name": "Bhagalpuri Silk",
    "slug": "bhagalpuri-silk",
    "parent_id": 4,
    "status": true
  },
  {
    "id": 21,
    "category_name": "Sikki Grass Craft",
    "slug": "sikki-grass-craft",
    "parent_id": 4,
    "status": true
  },
  {
    "id": 22,
    "category_name": "Diwali Puja Kit",
    "slug": "diwali-puja-kit",
    "parent_id": 5,
    "status": true
  },
  {
    "id": 23,
    "category_name": "Durga Puja Kit",
    "slug": "durga-puja-kit",
    "parent_id": 5,
    "status": true
  },
  {
    "id": 24,
    "category_name": "Satyanarayan Puja Kit",
    "slug": "satyanarayan-puja-kit",
    "parent_id": 5,
    "status": true
  }
];

const DEFAULT_PRODUCTS = [
  {
    "id": "shahi-litchi",
    "title": "Certified Shahi Litchi",
    "category": "fruits-fresh-produce",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": true,
    "season": "summer",
    "price": 240.0,
    "unit": "Per Kg (approx. 40-45 units)",
    "image": "assets/shahi_litchi.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Certified Shahi Litchi from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Certified Shahi Litchi supports sustainable local livelihood cooperatives."
  },
  {
    "id": "jardalu-mango",
    "title": "Bhagalpur Jardalu Mango",
    "category": "fruits-fresh-produce",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": true,
    "season": "summer",
    "price": 190.0,
    "unit": "Per Kg (approx. 4-5 units)",
    "image": "assets/jardalu_mango.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Bhagalpur Jardalu Mango from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Bhagalpur Jardalu Mango supports sustainable local livelihood cooperatives."
  },
  {
    "id": "organic-jamun",
    "title": "Wild Organic Jamun (Black Plum)",
    "category": "fruits-fresh-produce",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": true,
    "season": "summer",
    "price": 180.0,
    "unit": "Pack of 500g",
    "image": "",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Wild Organic Jamun (Black Plum) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Wild Organic Jamun (Black Plum) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "mithila-makhana",
    "title": "Premium Mithila Makhana",
    "category": "superfoods-snacks",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 380.0,
    "unit": "Pack of 500g (Jumbo Size)",
    "image": "assets/mithila_makhana.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Premium Mithila Makhana from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Premium Mithila Makhana supports sustainable local livelihood cooperatives."
  },
  {
    "id": "bhuna-makhana",
    "title": "Bhuna Makhana (Roasted Foxnuts)",
    "category": "superfoods-snacks",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 150.0,
    "unit": "Pack of 200g",
    "image": "assets/mithila_makhana.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Bhuna Makhana (Roasted Foxnuts) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Bhuna Makhana (Roasted Foxnuts) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "makhana-kheer-kit",
    "title": "Mithila Makhana Kheer Mix",
    "category": "superfoods-snacks",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 250.0,
    "unit": "Pack of 300g (Ready Pudding Mix)",
    "image": "assets/mithila_makhana.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Mithila Makhana Kheer Mix from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Mithila Makhana Kheer Mix supports sustainable local livelihood cooperatives."
  },
  {
    "id": "katarni-rice",
    "title": "Fragrant Katarni Rice",
    "category": "staples-grains",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 130.0,
    "unit": "Pack of 1 Kg",
    "image": "assets/katarni_rice.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Fragrant Katarni Rice from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Fragrant Katarni Rice supports sustainable local livelihood cooperatives."
  },
  {
    "id": "bhagalpuri-rice",
    "title": "Bhagalpuri Rice",
    "category": "staples-grains",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 110.0,
    "unit": "Pack of 1 Kg",
    "image": "assets/katarni_rice.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Bhagalpuri Rice from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Bhagalpuri Rice supports sustainable local livelihood cooperatives."
  },
  {
    "id": "chana-sattu",
    "title": "Chana ka Sattu (Gram Sattu)",
    "category": "staples-grains",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 90.0,
    "unit": "Pack of 1 Kg",
    "image": "assets/traditional_sattu.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Chana ka Sattu (Gram Sattu) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Chana ka Sattu (Gram Sattu) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "chura-poha",
    "title": "Chura / Poha / Avlaki",
    "category": "staples-grains",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 80.0,
    "unit": "Pack of 500g",
    "image": "assets/katarni_rice.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Chura / Poha / Avlaki from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Chura / Poha / Avlaki supports sustainable local livelihood cooperatives."
  },
  {
    "id": "silao-khaja",
    "title": "Famous Silao Khaja (GI Tagged)",
    "category": "superfoods-snacks",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 220.0,
    "unit": "Pack of 500g (12 Pieces)",
    "image": "assets/silao_khaja.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Famous Silao Khaja (GI Tagged) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Famous Silao Khaja (GI Tagged) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "gaya-sesame-tilkut",
    "title": "Gaya Special Sesame Tilkut",
    "category": "superfoods-snacks",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 280.0,
    "unit": "Pack of 500g",
    "image": "assets/gaya_tilkut.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Gaya Special Sesame Tilkut from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Gaya Special Sesame Tilkut supports sustainable local livelihood cooperatives."
  },
  {
    "id": "chhath-thekua",
    "title": "Authentic Chhath Prasad Thekua",
    "category": "superfoods-snacks",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 240.0,
    "unit": "Pack of 500g (Approx 16-18 pcs)",
    "image": "assets/thekua.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Authentic Chhath Prasad Thekua from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Authentic Chhath Prasad Thekua supports sustainable local livelihood cooperatives."
  },
  {
    "id": "sesame-anarsa",
    "title": "Traditional Sesame Anarsa",
    "category": "superfoods-snacks",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 260.0,
    "unit": "Pack of 500g",
    "image": "assets/anarsa.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Traditional Sesame Anarsa from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Traditional Sesame Anarsa supports sustainable local livelihood cooperatives."
  },
  {
    "id": "organic-jaggery",
    "title": "Organic Jaggery (Bheli)",
    "category": "superfoods-snacks",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 120.0,
    "unit": "Pack of 1 Kg",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Organic Jaggery (Bheli) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Organic Jaggery (Bheli) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "traditional-sweets",
    "title": "Traditional Sweets",
    "category": "superfoods-snacks",
    "isGI": false,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 599.0,
    "unit": "Pack of 1 Kg",
    "image": "assets/Sweets.avif",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Traditional Sweets from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Traditional Sweets supports sustainable local livelihood cooperatives."
  },
  {
    "id": "diwali-puja-package",
    "title": "Diwali Sacred Puja Package",
    "category": "puja-essentials-kits",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 450.0,
    "unit": "Complete Kit (12 items)",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Diwali Sacred Puja Package from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Diwali Sacred Puja Package supports sustainable local livelihood cooperatives."
  },
  {
    "id": "durgapuja-package",
    "title": "Durga Puja Sacred Package",
    "category": "puja-essentials-kits",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 550.0,
    "unit": "Complete Kit (15 items)",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Durga Puja Sacred Package from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Durga Puja Sacred Package supports sustainable local livelihood cooperatives."
  },
  {
    "id": "satyanarayan-puja-package",
    "title": "Satyanarayan Bhagwan Puja Package",
    "category": "puja-essentials-kits",
    "isGI": false,
    "isOrganic": true,
    "isSeasonal": false,
    "season": "winter",
    "price": 380.0,
    "unit": "Complete Kit (10 items)",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Satyanarayan Bhagwan Puja Package from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Satyanarayan Bhagwan Puja Package supports sustainable local livelihood cooperatives."
  },
  {
    "id": "madhubani-paintings",
    "title": "Madhubani Paintings (GI Tagged)",
    "category": "handlooms-handicrafts",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 650.0,
    "unit": "Handmade Canvas (A4 Size)",
    "image": "assets/mithila_makhana.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Madhubani Paintings (GI Tagged) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Madhubani Paintings (GI Tagged) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "bhagalpuri-silk",
    "title": "Bhagalpuri Silk (Tussar Stole)",
    "category": "handlooms-handicrafts",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 750.0,
    "unit": "Premium Silk Stole (2 Meters)",
    "image": "assets/katarni_rice.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Bhagalpuri Silk (Tussar Stole) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Bhagalpuri Silk (Tussar Stole) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "sikki-grass-craft",
    "title": "Sikki Grass Craft Basket",
    "category": "handlooms-handicrafts",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 290.0,
    "unit": "Handwoven Utility Box",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Sikki Grass Craft Basket from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Sikki Grass Craft Basket supports sustainable local livelihood cooperatives."
  },
  {
    "id": "kashmiri-kesar",
    "title": "Grade A++ Kashmiri Kesar (Saffron)",
    "category": "superfoods-snacks",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 350.0,
    "unit": "Pack of 1 Gram",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Grade A++ Kashmiri Kesar (Saffron) from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Grade A++ Kashmiri Kesar (Saffron) supports sustainable local livelihood cooperatives."
  },
  {
    "id": "darjeeling-tea",
    "title": "Darjeeling First Flush Black Tea",
    "category": "staples-grains",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 450.0,
    "unit": "Pack of 250g",
    "image": "assets/katarni_rice.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Darjeeling First Flush Black Tea from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Darjeeling First Flush Black Tea supports sustainable local livelihood cooperatives."
  },
  {
    "id": "mysore-sandalwood",
    "title": "Pure Mysore Sandalwood Oil",
    "category": "handlooms-handicrafts",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": false,
    "season": "winter",
    "price": 950.0,
    "unit": "Bottle of 5ml",
    "image": "assets/puja_box.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Pure Mysore Sandalwood Oil from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Pure Mysore Sandalwood Oil supports sustainable local livelihood cooperatives."
  },
  {
    "id": "alphonso-mango",
    "title": "Devgad Alphonso Hapus Mangoes",
    "category": "fruits-fresh-produce",
    "isGI": true,
    "isOrganic": false,
    "isSeasonal": true,
    "season": "summer",
    "price": 850.0,
    "unit": "Box of 6 Pieces",
    "image": "assets/jardalu_mango.jpg",
    "origin": "Bihar, India",
    "popularity": 95,
    "inStock": true,
    "description": "Premium authentic Devgad Alphonso Hapus Mangoes from our farmer cooperatives.",
    "heritageStory": "Handpicked and naturally sourced by ZoloFresh farmers. This authentic Devgad Alphonso Hapus Mangoes supports sustainable local livelihood cooperatives."
  }
];
